### ISSUE TITLE
目次コンポーネントの高さが短い場合 `activeId` に従って表示領域をスクロールしたい

### ISSUE THREAD

**Issue by ghost** [dninomiya/use-toc#2]
目次コンポーネント `<TOC />` 内の目次箇所も `overflow: scroll` にした場合 `activeId` な `heading` の `li` が表示される位置までスクロールさせたい

**Comment by dninomiya** [comment]
追加しました！

`tocContainer` props にクエリセレクタを渡すとその目次がスクロール追従するようになります。

https://github.com/dninomiya/use-toc/commit/cf51896fa7199e55f9febd9544e2cd43969a027f
