### ISSUE TITLE
`level` がすべて `NaN` になっている

### ISSUE THREAD

**Issue by ghost** [dninomiya/use-toc#3]
テスト実行ブラウザ環境: Safari / Chorome

```
heading.tagName.replace('h', '')
```

`tagName` は大文字で返却されている  // TODO: ブラウザによる可能性もあるか？

返却される値が `H1` などのようになるので `'h'` では `replace` されないために `NaN` が代入される

```
level: Number(heading.tagName.toLowerCase().replace('h', '')),
```

のように小文字にして `replace` する方が良いのでは？

**Comment by dninomiya** [comment]
実装ミスだったので修正しました！ありがとうございます！
